name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      uses: Instrument/github-tag-action@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        BUMP:  ${{ github.event.inputs.version }}
