name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: get_latest_releases
        name: Get latest releases
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query release($owner:String!, $name:String) {
              repository(owner: $owner, name: $name) {
                releases(first: 2, orderBy: {field: CREATED_AT, direction: DESC}) {
                  nodes {
                    name
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        env:
          PREVIOUS_TAG: ${{ fromJSON(steps.get_latest_releases.outputs.data).repository.releases.nodes[1].name }}
        run: |
          changelog=$(git log --color=never --pretty='tformat:%xe2%x80%xa2 `%h` %s (%an)' --tags $GITHUB_REF_NAME...$PREVIOUS_TAG)
          echo "CHANGELOG=$changelog" >> $GITHUB_ENV
          echo "TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Notify job status
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "channel": "C04CJ5PV22C",
              "username": "Release",
              "icon_url": "https://avatars.githubusercontent.com/u/1534766",
              "attachments": [
                {
                  "pretext": "`jus-cli` released :rocket:",
                  "color": "#008000",
                  "fields": [
                    {
                      "title": "Version",
                      "value": "<https://github.com/jusbrasil/jus-cli/releases/tag/${{ env.TAG }}|${{ env.TAG }}>",
                      "short": false
                    },
                    {
                      "title": "Changelog",
                      "value": "${{ env.CHANGELOG }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
